repos:
- id: "/.*/"
  workflow: terrascan
workflows:
    terrascan:
     plan:
        steps:
        - run: terraform init -input=false -no-color
        - run: terraform workspace select -no-color $WORKSPACE
        - run: terraform plan -input=false -refresh -no-color -out $PLANFILE
        - run: terraform show -no-color -json $PLANFILE > ${PLANFILE}.json
        - run: /terrascan.sh